"use client";
import Link from "next/link";
import { useMemo, useState } from "react";
import { useDeleteLeadMutation, useLeadsQuery } from "@/features/leads/hooks";
import { ErrorState, LoadingState, EmptyState } from "@/components/shared/state";
import { StageBadge } from "@/components/shared/stage-badge";
import { formatDate } from "@/lib/format";
type SortField = "id"|"name"|"source"|"stage"|"created_at"; type SortDirection = "asc"|"desc";
export default function LeadsPage(){ const [page,setPage]=useState(1); const [search,setSearch]=useState(""); const [stage,setStage]=useState(""); const [source,setSource]=useState(""); const [sortBy,setSortBy]=useState<SortField>("created_at"); const [sortDir,setSortDir]=useState<SortDirection>("desc");
const filters=useMemo(()=>({page,search:search||undefined,stage:stage||undefined,source:source||undefined,sort_by:sortBy,sort_dir:sortDir}),[page,search,stage,source,sortBy,sortDir]);
const query=useLeadsQuery(filters); const deleteMutation=useDeleteLeadMutation();
function toggleSort(field:SortField){ if(sortBy===field){ setSortDir(current=>current==="asc"?"desc":"asc"); return;} setSortBy(field); setSortDir("asc");}
function handleDelete(id:number){ if(!window.confirm("Delete this lead?")) return; deleteMutation.mutate(id);}
return <div className="container"><div className="page-header"><div><h1>Leads</h1><div className="muted">Filter, sort, browse, and manage your leads.</div></div><div className="inline"><Link href="/dashboard" className="btn ghost">Dashboard</Link><Link href="/leads/kanban" className="btn">Kanban</Link></div></div>
<div className="card"><div className="filters"><input className="input" placeholder="Search by name, email, or phone" value={search} onChange={(e)=>{setSearch(e.target.value);setPage(1);}} />
<select className="select" value={stage} onChange={(e)=>{setStage(e.target.value);setPage(1);}}><option value="">All stages</option><option value="new">New</option><option value="contacted">Contacted</option><option value="follow_up">Follow up</option><option value="assigned">Assigned</option><option value="converted">Converted</option><option value="lost">Lost</option></select>
<select className="select" value={source} onChange={(e)=>{setSource(e.target.value);setPage(1);}}><option value="">All sources</option><option value="facebook">Facebook</option><option value="whatsapp">WhatsApp</option><option value="website">Website</option><option value="manual">Manual</option></select>
<button className="btn secondary" onClick={()=>{setSearch("");setStage("");setSource("");setSortBy("created_at");setSortDir("desc");setPage(1);}}>Reset Filters</button><div className="muted" style={{alignSelf:"center"}}>Showing page {page}</div></div>
{query.isLoading?<LoadingState text="Loading leads..." />:query.isError?<ErrorState message="Failed to load leads." />:!query.data?.data.length?<EmptyState text="No leads found for the selected filters." />:<><div className="table-wrap"><table className="table"><thead><tr><th><button onClick={()=>toggleSort("id")}>ID</button></th><th><button onClick={()=>toggleSort("name")}>Name</button></th><th>Phone</th><th>Email</th><th><button onClick={()=>toggleSort("source")}>Source</button></th><th><button onClick={()=>toggleSort("created_at")}>Date</button></th><th><button onClick={()=>toggleSort("stage")}>Stage</button></th><th>Assigned</th><th>Actions</th></tr></thead><tbody>{query.data.data.map((lead)=><tr key={lead.id}><td>{lead.id}</td><td>{lead.name}</td><td>{lead.phone||"—"}</td><td>{lead.email||"—"}</td><td>{lead.source}</td><td>{formatDate(lead.created_at)}</td><td><StageBadge stage={lead.stage} /></td><td>{lead.assigned_user?.name||"Unassigned"}</td><td><div className="actions"><Link href={`/leads/${lead.id}`} className="btn ghost">View</Link><button className="btn danger" onClick={()=>handleDelete(lead.id)} disabled={deleteMutation.isPending}>Delete</button></div></td></tr>)}</tbody></table></div><div className="page-header" style={{marginTop:16,marginBottom:0}}><div className="muted">Total: {query.data.meta.total} leads</div><div className="inline"><button className="btn secondary" disabled={page<=1} onClick={()=>setPage(p=>Math.max(1,p-1))}>Previous</button><div className="muted">Page {query.data.meta.current_page} of {query.data.meta.last_page}</div><button className="btn secondary" disabled={page>=query.data.meta.last_page} onClick={()=>setPage(p=>p+1)}>Next</button></div></div></>}</div></div>; }
