"use client";
import Link from "next/link";
import { BarChart, Bar, CartesianGrid, PieChart, Pie, Cell, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { useLeadStatsQuery, useLeadsQuery } from "@/features/leads/hooks";
import { LoadingState, ErrorState, EmptyState } from "@/components/shared/state";
import { StageBadge } from "@/components/shared/stage-badge";
import { formatDate } from "@/lib/format";
const colors=["#2563eb","#16a34a","#d97706","#7c3aed","#0f766e","#dc2626"];
export default function DashboardPage(){ const statsQuery=useLeadStatsQuery(); const recentQuery=useLeadsQuery({page:1,sort_by:"created_at",sort_dir:"desc"}); if(statsQuery.isLoading||recentQuery.isLoading) return <div className="container"><LoadingState text="Loading dashboard..." /></div>; if(statsQuery.isError||recentQuery.isError) return <div className="container"><ErrorState message="Failed to load dashboard data." /></div>; const stats=statsQuery.data!; const recent=recentQuery.data!.data.slice(0,5); const stageData=Object.entries(stats.by_stage).map(([name,value])=>({name,value})); const sourceData=Object.entries(stats.by_source).map(([name,value])=>({name,value}));
return <div className="container"><div className="page-header"><div><h1>Dashboard</h1><div className="muted">Overview of total leads, stages, sources, and recent activity.</div></div></div>
<div className="grid grid-4"><div className="card"><div className="muted">Total Leads</div><div className="stat-value">{stats.total}</div></div>{Object.entries(stats.by_stage).slice(0,3).map(([stage,count])=><div className="card" key={stage}><div className="muted">Stage</div><div className="inline" style={{justifyContent:"space-between"}}><StageBadge stage={stage} /><div className="stat-value" style={{fontSize:22}}>{count}</div></div></div>)}</div>
<div className="grid grid-2" style={{marginTop:16}}><div className="card"><h2 className="section-title">Leads by Stage</h2><div style={{width:"100%",height:320}}><ResponsiveContainer><BarChart data={stageData}><CartesianGrid strokeDasharray="3 3" /><XAxis dataKey="name" /><YAxis allowDecimals={false} /><Tooltip /><Bar dataKey="value" fill="#2563eb" radius={[6,6,0,0]} /></BarChart></ResponsiveContainer></div></div>
<div className="card"><h2 className="section-title">Leads by Source</h2><div style={{width:"100%",height:320}}><ResponsiveContainer><PieChart><Pie data={sourceData} dataKey="value" nameKey="name" outerRadius={110} label>{sourceData.map((_,i)=><Cell key={i} fill={colors[i%colors.length]} />)}</Pie><Tooltip /></PieChart></ResponsiveContainer></div></div></div>
<div className="card" style={{marginTop:16}}><div className="page-header" style={{marginBottom:12}}><h2 className="section-title" style={{marginBottom:0}}>Recent Leads</h2><Link href="/leads" className="btn ghost">Open Leads</Link></div>{!recent.length?<EmptyState text="No leads found." />:<div className="table-wrap"><table className="table"><thead><tr><th>ID</th><th>Name</th><th>Source</th><th>Stage</th><th>Date</th></tr></thead><tbody>{recent.map((lead)=><tr key={lead.id}><td>{lead.id}</td><td><Link href={`/leads/${lead.id}`} style={{color:"#2563eb",fontWeight:700}}>{lead.name}</Link></td><td>{lead.source}</td><td><StageBadge stage={lead.stage} /></td><td>{formatDate(lead.created_at)}</td></tr>)}</tbody></table></div>}</div></div>; }
